# Generated by Django 5.1.2 on 2025-08-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_country', models.CharField(max_length=150, unique=True)),
                ('icon_country', models.CharField(max_length=1000)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
