# Generated by Django 5.1.2 on 2025-08-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_date_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_birthday',
            field=models.DateField(blank=True, default='1993-10-10', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
