# Generated by Django 5.1.2 on 2025-08-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_date_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='static/image/default.jpg', null=True, upload_to='static/image/'),
        ),
    ]
