# Generated by Django 5.1.2 on 2025-08-24 14:33

import django.db.models.deletion
import accounts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_one', models.ImageField(blank=True, default='static/image/default.jpg', null=True, upload_to=accounts.models.user_image_path)),
                ('image_tow', models.ImageField(blank=True, default='static/image/default.jpg', null=True, upload_to=accounts.models.user_image_path)),
                ('image_thriy', models.ImageField(blank=True, default='static/image/default.jpg', null=True, upload_to=accounts.models.user_image_path)),
                ('image_four', models.ImageField(blank=True, default='static/image/default.jpg', null=True, upload_to=accounts.models.user_image_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
