# Generated by Django 5.1.2 on 2025-08-25 21:08

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_image',
            name='image_four',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_image_path),
        ),
        migrations.AlterField(
            model_name='user_image',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_image_path),
        ),
        migrations.AlterField(
            model_name='user_image',
            name='image_thriy',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_image_path),
        ),
        migrations.AlterField(
            model_name='user_image',
            name='image_tow',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_image_path),
        ),
    ]
