# Generated by Django 5.1.2 on 2025-08-26 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang', '0001_initial'),
        ('accounts', '0007_alter_user_image_image_four_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='lang_mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lang.langs'),
        ),
    ]
