# Generated by Django 5.1.2 on 2025-09-01 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_lang_mother'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='follow_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_follow', models.BooleanField(default=True)),
                ('receiver_follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_follow', to=settings.AUTH_USER_MODEL)),
                ('sender_follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_follow', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
