# Generated by Django 5.1.2 on 2025-09-06 18:15

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_follow_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_image',
            name='image_four',
            field=models.ImageField(blank=True, default='static/image/default.jpg', null=True, upload_to=accounts.models.user_image_path),
        ),
        migrations.AlterField(
            model_name='user_image',
            name='image_one',
            field=models.ImageField(blank=True, default='static/image/default.jpg', null=True, upload_to=accounts.models.user_image_path),
        ),
        migrations.AlterField(
            model_name='user_image',
            name='image_thriy',
            field=models.ImageField(blank=True, default='static/image/default.jpg', null=True, upload_to=accounts.models.user_image_path),
        ),
        migrations.AlterField(
            model_name='user_image',
            name='image_tow',
            field=models.ImageField(blank=True, default='static/image/default.jpg', null=True, upload_to=accounts.models.user_image_path),
        ),
    ]
