# Generated by Django 5.2.4 on 2026-04-01 15:44

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_image_image_four_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='static/image/default.jpg', upload_to=accounts.models.user_image_path),
        ),
    ]
