# Generated by Django 5.2.4 on 2026-04-01 15:47

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_image',
            name='image_four',
            field=models.ImageField(default='static/image/default.jpg', upload_to=accounts.models.user_image_path),
        ),
        migrations.AlterField(
            model_name='user_image',
            name='image_one',
            field=models.ImageField(default='static/image/default.jpg', upload_to=accounts.models.user_image_path),
        ),
        migrations.AlterField(
            model_name='user_image',
            name='image_thriy',
            field=models.ImageField(default='static/image/default.jpg', upload_to=accounts.models.user_image_path),
        ),
        migrations.AlterField(
            model_name='user_image',
            name='image_tow',
            field=models.ImageField(default='static/image/default.jpg', upload_to=accounts.models.user_image_path),
        ),
    ]
